# Site settings
title: Inversed Technologies
description: building the future of the open internet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Inversed Tech
user_description: We work on research and development with open source ecosystems to bring the state-of-the-art cryptography to the top protocols in the web3 and blockchain space, contributing meaningfully to the development of their functionality, security, interoperability and efficiency.
email: info@inversed.tech
twitter_username: inversed_tech
github_username:  Inversed-Tech

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
